services:
  redis-7001:
    image: redis:7.4.2
    volumes:
      - ./7001/redis.conf:/etc/redis/redis.conf:ro
      - redis_7001_data:/data/redis/master
    command: redis-server /etc/redis/redis.conf
    ports:
      - "7001:7001"

  redis-7002:
    image: redis:7.4.2
    volumes:
      - ./7002/redis.conf:/etc/redis/redis.conf:ro
      - redis_7002_data:/data/redis/master
    command: redis-server /etc/redis/redis.conf
    ports:
      - "7002:7002"

  redis-7003:
    image: redis:7.4.2
    volumes:
      - ./7003/redis.conf:/etc/redis/redis.conf:ro
      - redis_7003_data:/data/redis/master
    command: redis-server /etc/redis/redis.conf
    ports:
      - "7003:7003"

  redis-7004:
    image: redis:7.4.2
    volumes:
      - ./7004/redis.conf:/etc/redis/redis.conf:ro
      - redis_7004_data:/data/redis/master
    command: redis-server /etc/redis/redis.conf
    ports:
      - "7004:7004"

  redis-7005:
    image: redis:7.4.2
    volumes:
      - ./7005/redis.conf:/etc/redis/redis.conf:ro
      - redis_7005_data:/data/redis/master
    command: redis-server /etc/redis/redis.conf
    ports:
      - "7005:7005"

  redis-7006:
    image: redis:7.4.2
    volumes:
      - ./7006/redis.conf:/etc/redis/redis.conf:ro
      - redis_7006_data:/data/redis/master
    command: redis-server /etc/redis/redis.conf
    ports:
      - "7006:7006"

  redis-7007:
    image: redis:7.4.2
    volumes:
      - ./7007/redis.conf:/etc/redis/redis.conf:ro
      - redis_7007_data:/data/redis/master
    command: redis-server /etc/redis/redis.conf
    ports:
      - "7007:7007"

  redis-7008:
    image: redis:7.4.2
    volumes:
      - ./7008/redis.conf:/etc/redis/redis.conf:ro
      - redis_7008_data:/data/redis/master
    command: redis-server /etc/redis/redis.conf
    ports:
      - "7008:7008"

  redis:
    image: redis:7.4.2
    command: [ "sh", "/init-redis.sh" ]
    volumes:
      - ./init-redis.sh:/init-redis.sh
    depends_on:
      - redis-7001
      - redis-7002
      - redis-7003
      - redis-7004
      - redis-7005
      - redis-7006
      - redis-7007
      - redis-7008

volumes:
  redis_7001_data:
  redis_7002_data:
  redis_7003_data:
  redis_7004_data:
  redis_7005_data:
  redis_7006_data:
  redis_7007_data:
  redis_7008_data: